### ISSUE TITLE
[Question] How do you handle custom regex/configurations which are not bundled with fail2ban?

### ISSUE THREAD

**Issue by renepardon** [infOpen/ansible-role-fail2ban#6]
I'ld like to use some custom configurations/regexes/jails. How would you implement this using your amazing ansible role?

Best

**Comment by achaussier** [comment]
Hello,

With the current version, you can define custom jails using `fail2ban_services` variable. You can find an example here : https://github.com/infOpen/ansible-role-fail2ban/blob/master/vars/os_distribution/ubuntu/xenial.yml

I'll update this role in the next days to apply a new structure and testing management.
If you have some ideas to improve the role, you can create issues, I'll take a look at the same time.

Alexandre

**Comment by renepardon** [comment]
Thank you!

I managed it to get it working with a pre-task to create the fail2ban/filter.d folder if it doesn't exist and then copy all non-existing templates to this folder.

Playbook:
```yaml
---
- hosts: all
  become: yes
  become_user: root
  pre_tasks:
    - include: tasks/pre/load_vars.yml
    - include: tasks/pre/fail2ban.yml
  roles:
    - role: community/infOpen.fail2ban
```

Pre-Task:

```yaml
---
- name: fail2ban | ensure /etc/fail2ban/filter.d exists
  file:
    path: /etc/fail2ban/filter.d
    owner: root
    group: root
    mode: "u+rwx,g-xr,o-x"
    state: directory

- name: fail2ban | copy configuration files to the server
  template: src={{ item }} dest=/etc/fail2ban/filter.d/{{ item | basename | regex_replace('\.j2','') }}
  with_fileglob:
    - templates/fail2ban/filters/*.j2
```
